main:
  - identifier: about
    name: About
    pageRef: /about
    weight: 100
  - identifier: reviews
    name: Reviews
    pageRef: /reviews
    weight: 200
  - identifier: on-location
    name: "#OnLocation"
    pageRef: /on-location
    weight: 300
