main:
  - identifier: about
    name: About
    url: /about
    weight: 100
  - identifier: reviews
    name: Reviews
    url: /reviews
    weight: 200
  - identifier: on-location
    name: "#OnLocation"
    url: /on-location
    weight: 300
