main:
  - identifier: about
    name: About
    pageRef: /about
    weight: 100
  - identifier: reviews
    name: Reviews
    pageRef: /reviews
    weight: 200
  - identifier: traveleats
    name: "#TravelEats"
    pageRef: /series/traveleats
    weight: 300
