post_content_classes: avenir next
site_logo: "image/NairobiEats-Logo-White.png"
title: "NairobiEats"
description: "Welcome to Nairobi Eats, your one-stop shop for restaurant reviews within Nairobi and beyond!"
recent_copy: "Featured Reviews"
aside_image: "" # for promotions in the article page
# mainSections: "featured"
images:
  - "image/NairobiEats-Logo-Black-rectangle.png"
custom_css:
  - lightbox.css
social:
  twitter: https://x.com/nairobieats
ananke_socials:
  - name: twitter
    url: https://x.com/nairobieats
    label: Twitter
  - name: instagram
    url: https://www.instagram.com/nairobi.eats/
    label: Instagram
search:
  filter_taxonomies: false
  filter_years: false
  threshold: 0.4
  index_content: true
  max_results: 10
  min_match_char_length: 2
