post_content_classes: avenir next
site_logo: "image/NairobiEats-Logo-White.png"
description: "Welcome to Nairobi Eats, your one-stop shop for restaurant reviews within Nairobi and beyond!"
custom_css:
  - lightbox.css
ananke_socials:
  - name: twitter
    url: https://twitter.com/_brianmarete/status/1631598293414457344
    label: Twitter
  - name: instagram
    url: https://www.instagram.com/nairobi.eats/
    label: Instagram
