includeNewer: true
threshold: 90
toLower: false
indices:
  - name: keywords
    applyFilter: false
    pattern: ""
    toLower: false
    type: basic
    weight: 100
  - name: tags
    applyFilter: false
    pattern: ""
    toLower: false
    type: basic
    weight: 90
