baseURL = 'https://nairobieats.co.ke/'
languageCode = 'en-us'
title = 'Nairobi Eats'
theme = "ananke"
disqusShortname = 'nairobieats'

[markup.goldmark.renderer]
unsafe = true

[params]
post_content_classes = 'avenir next'

[services]
  [services.googleAnalytics]
    ID = 'G-XTPPNNQL5X'